name: Practice 2
on: [issues]
jobs:
  outputs:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Event details
        run: echo ${{ toJson(github.event) }}
      - name: Issue event
        if: github.event_name == 'issues'
        run: echo ${{ toJson(github.event.issue) }}
      - name: Github context
        run: echo ${{ toJson(github) }}
